### ISSUE TITLE
How would you set up the server it connects to?

### ISSUE THREAD

**Issue by ghost** [anKordii/Capes-Installer#2]
The local hosted server that gets added to hosts how should it be set up? With cape pngs or user names?

**Comment by anKordii** [comment]
Usernames

**Comment by anKordii** [comment]
> The local hosted server that gets added to hosts how should it be set up? With cape pngs or user names?

Usernames

**Comment by ghost** [comment]
Do you put the usernames on a regular html server or a mysql and how do you change the designs of the capes/add capes

**Comment by anKordii** [comment]
I mean you just need to create png file named like user, with cape desgin he want, so i prob would do a simpel nodejs server or php file that on request create image from x template and naming as in request 

> Do you put the usernames on a regular html server or a mysql and how do you change the designs of the capes/add capes

**Comment by ghost** [comment]
Can you provide a node JS template? I'm fine with making my own but don't exactly understand what you mean.
