### ISSUE TITLE
Jak nadać i skonfigurować?

### ISSUE THREAD

**Issue by ghost** [anKordii/Capes-Installer#3]
Cześć, jak zrobić, że jakiś gracz ma pelerynke?

**Comment by anKordii** [comment]
@PieczarkaDev 
# Wstęp
No na serwerze gdzie przekierowujesz domenę optifine.net, tworzysz plik **.png** z nazwą konta np. **h1tps.png**
![h1tps](https://user-images.githubusercontent.com/34755589/171273289-2e7123ef-c70a-4267-ab7f-6a4f67f8de89.png) i śmiga.

# Dashboard/Panel
Jednak jeśli chodzi o jakiś panel/dashboard do tworzenia automatycznie plików png no to musisz już zrobić samemu, chyba najłatwiej będzie to zrobić w nodejs? Ale to już zależy od ciebie, w którym języku czujesz się najlepiej :D
